#------------------Edit these variables---------------------#
#Access token generated by an account admin
$auth_token = ''

#If your instance is utah.instructure.com, this is just 'utah'
$school_domain = ''

#The full path to the CSV mapping file
$input_file_path = "/path/to/file.csv"

#No need to edit this
$api_base_url = "https://#{$school_domain}.instructure.com/api/v1/"

#----------------------------------------------------------#
#  Don't edit from here unless you know what you are doing #
#----------------------------------------------------------#

#Required gems
require 'rubygems'
require 'json'
require 'typhoeus'
require 'csv'

#------------------Get Course Info------------------------#
# - Pulls information from the CSV File
#---------------------------------------------------------#

def read_file_data
  #open mapping file
  CSV.foreach($input_file_path, headers: true) do |row|

    if row['canvas_group_id'].nil?
      puts 'No data in canvas_group_id'
      raise 'Valid CSV headers not found (Expecting canvas_group_id)'
    else
      group_id = row['canvas_group_id']
      puts "deleting group id #{group_id}..."
      delete_group(group_id)
    end
  end
end

#------------------Delete Group----------------------#
#  - Delete the specified group in Canvas
#---------------------------------------------------------#
def delete_group(group_id)
  response = Typhoeus.delete(

          $api_base_url + "groups/#{group_id}",
          headers: {:authorization => 'Bearer ' + $auth_token}
      )
  #parse JSON data to save in readable array
  data = JSON.parse(response.body)

  puts data
end

#Initializes the script
read_file_data
puts "Finished"
